erickxnuxer/Sistem-Dashboard-Sekolah

- dashboard/data/tbhari/delete.php
> add delete.php

- dashboard/data/tbhari/func.php
> add tbhari func.php

- dashboard/data/tbhari/hari.php
> add tbhari hari.php

- dashboard/js/script-tbhari.js
> add js script-tbhari.js

- dashboard/data/tbhari/data.php
> add tbhari data.php

- dashboard/data/tbjam/func.php
> add func tbjam

- dashboard/data/tbjam/delete.php
> add delete tbjam

- dashboard/index.php
> add tbkelas index

- dashboard/data/tbjam/data.php
> add data tbjam

- dashboard/data/tbjam/jam.php
> add jam.php

- dashboard/js/script-tbjam.js
> add script tbjam

- dashboard/js/script-tbkelas.js
> add script tbkelas

- dashboard/data/tbkelas/kelas.php
> add kelas.php

- dashboard/data/tbkelas/func.php
> add func kelas

- dashboard/data/tbkelas/data.php
> add data kelas

- dashboard/data/tbkelas/delete.php
> add delete kelas

- dashboard/index.php
> add tbjam index 2

- dashboard/js/script-tbmapel.js
> Script-tbmapel.js

- dashboard/js/script-tbhari.js
> update js tbhari

- dashboard/data/tbhari/data.php
> update data tbhari

- dashboard/siswa.php
> perbaiki footer siswa.php

- dashboard/guru.php
> add guru.php

- dashboard/index.php
> update footer,logo index.php

- dashboard/guru.php
> update typo guru.php
